/**
 * BROKER MISSION ENCOUNTERS
 *
 * Mission destinations purchased from The Broker.
 * Each mission spawns zone enemies — the player must defeat 10 squads to clear it.
 * Appended to per-zone encounter arrays at load time.
 */

const ENCOUNTERS_MISSION = {
    scrapyard: {
        name: "Scout Factory",
        type: "shop",
        discoverable: true,
        isMission: true,
        missionKey: "Scrap Fields: Scout Factory",
        killsRequired: 10,
        description: "A hidden factory buried under the Scrap Fields. Automated assembly lines churn out light recon units around the clock.",
        engageText: "Your mech touches down outside a rusted hangar. Through the gash in the wall, you can see rows of half-assembled scout frames on conveyor belts. Sensors are already pinging incoming hostiles.",
        discoveredDescription: "The scout factory looms ahead, smoke rising from its vents. Assembly lines are still running.",
        discoveredEngageText: "You approach the factory perimeter. Your HUD flickers with proximity alerts. They're still producing.",
        completionText: "The last scout frame crumples. The assembly line grinds to a halt, sparks raining from severed power conduits. Mission complete.",
        completionItem: "Scout Factory Clearance",
        appearanceRate: 0,
        minLevel: 1,
        itemSlot1: null,
        itemSlot2: null,
        itemSlot3: null,
        itemSlot4: null
    },
    oldbattlefield: {
        name: "Munitions Bunker",
        type: "shop",
        discoverable: true,
        isMission: true,
        missionKey: "Old Battlefield: Munitions Bunker",
        killsRequired: 10,
        description: "A buried munitions bunker deep in the Old Battlefield. Automated defense protocols are still active.",
        engageText: "The bunker entrance is half-collapsed, blast doors wedged open by decades of debris. Your HUD lights up with movement signatures below. They know you're here.",
        discoveredDescription: "The bunker entrance gapes open, blast doors frozen at odd angles. Ammunition crates are stacked inside.",
        discoveredEngageText: "You descend into the bunker. Emergency lights flicker along the corridor. Movement ahead.",
        completionText: "The bunker falls silent. Ammo racks lie shattered across the floor. Nothing left worth fighting over. Mission complete.",
        completionItem: "Munitions Bunker Clearance",
        appearanceRate: 0,
        minLevel: 1,
        itemSlot1: null,
        itemSlot2: null,
        itemSlot3: null,
        itemSlot4: null
    },
    downtown: {
        name: "Signal Tower",
        type: "shop",
        discoverable: true,
        isMission: true,
        missionKey: "Downtown: Signal Tower",
        killsRequired: 10,
        description: "A rogue signal tower broadcasting encrypted rally commands to hostile units across the district.",
        engageText: "The tower looms above the skyline, its antenna array pulsing with crimson light. Armed patrols circle the perimeter. Your comms crackle with intercepted chatter — they're calling in reinforcements.",
        discoveredDescription: "The signal tower pulses red against the smog. Patrols circle its base in tight formation.",
        discoveredEngageText: "You close in on the tower. The broadcast frequency spikes — they've detected your approach.",
        completionText: "The signal tower's antenna array sparks and goes dark. The broadcast dies mid-transmission. The streets are quiet again. Mission complete.",
        completionItem: "Signal Tower Clearance",
        appearanceRate: 0,
        minLevel: 1,
        itemSlot1: null,
        itemSlot2: null,
        itemSlot3: null,
        itemSlot4: null
    },
    orbitalstation: {
        name: "Drone Foundry",
        type: "shop",
        discoverable: true,
        isMission: true,
        missionKey: "Orbital Station: Drone Foundry",
        killsRequired: 10,
        description: "A decommissioned module repurposed as a drone foundry. Swarms of attack drones are assembled and deployed from the bay.",
        engageText: "The airlock cycles open into a cavernous hangar. Drone chassis hang from ceiling rails like metal cocoons. The foundry hums with power — and the first wave of defenders is already airborne.",
        discoveredDescription: "The drone foundry hums behind sealed bulkheads. You can hear fabrication arms cycling inside.",
        discoveredEngageText: "The airlock grinds open. Rows of drone chassis swing overhead on assembly rails. Defenders scramble.",
        completionText: "The foundry's fabrication arms hang limp, drone chassis scattered across the bay floor. Production has ceased. Mission complete.",
        completionItem: "Drone Foundry Clearance",
        appearanceRate: 0,
        minLevel: 1,
        itemSlot1: null,
        itemSlot2: null,
        itemSlot3: null,
        itemSlot4: null
    },
    wasteland: {
        name: "Fuel Depot",
        type: "shop",
        discoverable: true,
        isMission: true,
        missionKey: "Wasteland: Fuel Depot",
        killsRequired: 10,
        description: "An irradiated fuel depot supplying hostile convoys across the region.",
        engageText: "Massive fuel tanks rise from the cracked earth like metal blisters. Geiger counters spike as you approach. Guard patrols emerge from behind the storage silos, weapons hot.",
        discoveredDescription: "The fuel depot squats on the horizon, heat shimmer rising from its irradiated tanks.",
        discoveredEngageText: "You push through the radiation haze. Fuel lines run in every direction. Guards are already mobilising.",
        completionText: "The fuel depot burns. Black smoke rises into the irradiated sky as the last defenders fall. Supply lines severed. Mission complete.",
        completionItem: "Fuel Depot Clearance",
        appearanceRate: 0,
        minLevel: 1,
        itemSlot1: null,
        itemSlot2: null,
        itemSlot3: null,
        itemSlot4: null
    },
    undercity: {
        name: "Nerve Centre",
        type: "shop",
        discoverable: true,
        isMission: true,
        missionKey: "Undercity: Nerve Centre",
        killsRequired: 10,
        description: "A tunnel command hub coordinating hostile activity across the pipe network.",
        engageText: "The tunnel opens into a vaulted chamber lined with flickering screens and tangled cables. A central console pulses with data. The guards stationed here don't look surprised to see you.",
        discoveredDescription: "The nerve centre's entrance is marked by bundled cables running along the tunnel ceiling.",
        discoveredEngageText: "You enter the chamber. Screens flicker with tactical data. The guards are already on their feet.",
        completionText: "The screens go black one by one. The command hub is silent, its operators scattered. The pipe network is blind. Mission complete.",
        completionItem: "Nerve Centre Clearance",
        appearanceRate: 0,
        minLevel: 1,
        itemSlot1: null,
        itemSlot2: null,
        itemSlot3: null,
        itemSlot4: null
    },
    industrialzone: {
        name: "Weapons Lab",
        type: "shop",
        discoverable: true,
        isMission: true,
        missionKey: "Industrial Zone: Weapons Lab",
        killsRequired: 10,
        description: "An R&D weapons lab hidden in the Industrial Zone developing prototype weapon systems.",
        engageText: "The lab is disguised as a defunct refinery. Inside, weapon prototypes line reinforced racks. Test-fire scorch marks cover every wall. Security teams are already moving to intercept.",
        discoveredDescription: "The weapons lab is hidden behind a refinery facade. Scorch marks line every visible surface.",
        discoveredEngageText: "You breach the outer wall. Prototype racks line the corridors. Security is moving to intercept.",
        completionText: "The weapons lab is gutted. Prototype schematics burn in the wreckage. Whatever they were building, it dies here. Mission complete.",
        completionItem: "Weapons Lab Clearance",
        appearanceRate: 0,
        minLevel: 1,
        itemSlot1: null,
        itemSlot2: null,
        itemSlot3: null,
        itemSlot4: null
    },
    frozenreach: {
        name: "Cryo Vault",
        type: "shop",
        discoverable: true,
        isMission: true,
        missionKey: "Frozen Reach: Cryo Vault",
        killsRequired: 10,
        description: "A cryo vault storing high-value military assets in deep freeze. Someone's been thawing them out.",
        engageText: "Ice crunches under your mech's weight as the vault doors grind open. Rows of frozen chassis line the walls, frost crystallising on their armour. The defrosting cycle has already begun on the nearest row.",
        discoveredDescription: "The cryo vault's doors are wedged open. Frost billows from the entrance in thick clouds.",
        discoveredEngageText: "You step inside. Frozen chassis line the walls. The defrost cycle hums. Defenders are thawing.",
        completionText: "The cryo vault's cooling systems fail. Meltwater pools across the floor as the last defenders fall. Nothing left to thaw. Mission complete.",
        completionItem: "Cryo Vault Clearance",
        appearanceRate: 0,
        minLevel: 1,
        itemSlot1: null,
        itemSlot2: null,
        itemSlot3: null,
        itemSlot4: null
    },
    neonstrip: {
        name: "Syndicate Arena",
        type: "shop",
        discoverable: true,
        isMission: true,
        missionKey: "Neon Strip: Syndicate Arena",
        killsRequired: 10,
        description: "A syndicate-run gladiator arena pitting captured mechs against each other for profit.",
        engageText: "The arena's neon sign flickers overhead: 'IRON & BLOOD'. Inside, the pit is stained with hydraulic fluid and scorched metal. The house champions are already warming up.",
        discoveredDescription: "The arena's neon sign buzzes overhead. You can hear the crowd and the grind of metal inside.",
        discoveredEngageText: "You enter the pit. The crowd roars. The house champions step forward, weapons primed.",
        completionText: "The arena lights go out. The last champion drops. The crowd — what's left of it — scatters into the neon-lit streets. The show is over. Mission complete.",
        completionItem: "Syndicate Arena Clearance",
        appearanceRate: 0,
        minLevel: 1,
        itemSlot1: null,
        itemSlot2: null,
        itemSlot3: null,
        itemSlot4: null
    },
    deadzone: {
        name: "Reactor Core",
        type: "shop",
        discoverable: true,
        isMission: true,
        missionKey: "Dead Zone: Reactor Core",
        killsRequired: 10,
        description: "A corrupted reactor core powering an entire network of hostile units. The radiation is lethal and the defenses are brutal.",
        engageText: "The reactor hums with a sickly green glow. Warning klaxons blare across the facility. Every system in your mech screams proximity alert as the heaviest resistance you've ever faced closes in.",
        discoveredDescription: "The reactor pulses with sickly green light. Warning klaxons echo across the dead terrain.",
        discoveredEngageText: "You breach the reactor perimeter. Klaxons scream. The heaviest resistance you've faced closes in.",
        completionText: "The reactor core destabilises and goes dark. The hum that powered a thousand war machines fades to silence. The Dead Zone just got a little quieter. Mission complete.",
        completionItem: "Reactor Core Clearance",
        appearanceRate: 0,
        minLevel: 1,
        itemSlot1: null,
        itemSlot2: null,
        itemSlot3: null,
        itemSlot4: null
    }
};

// Append mission encounters to each zone's encounter array
(function() {
    const zoneArrays = {
        scrapyard: typeof ENCOUNTERS_SCRAPYARD !== 'undefined' ? ENCOUNTERS_SCRAPYARD : null,
        oldbattlefield: typeof ENCOUNTERS_OLDBATTLEFIELD !== 'undefined' ? ENCOUNTERS_OLDBATTLEFIELD : null,
        downtown: typeof ENCOUNTERS_DOWNTOWN !== 'undefined' ? ENCOUNTERS_DOWNTOWN : null,
        orbitalstation: typeof ENCOUNTERS_ORBITALSTATION !== 'undefined' ? ENCOUNTERS_ORBITALSTATION : null,
        wasteland: typeof ENCOUNTERS_WASTELAND !== 'undefined' ? ENCOUNTERS_WASTELAND : null,
        undercity: typeof ENCOUNTERS_UNDERCITY !== 'undefined' ? ENCOUNTERS_UNDERCITY : null,
        industrialzone: typeof ENCOUNTERS_INDUSTRIALZONE !== 'undefined' ? ENCOUNTERS_INDUSTRIALZONE : null,
        frozenreach: typeof ENCOUNTERS_FROZENREACH !== 'undefined' ? ENCOUNTERS_FROZENREACH : null,
        neonstrip: typeof ENCOUNTERS_NEONSTRIP !== 'undefined' ? ENCOUNTERS_NEONSTRIP : null,
        deadzone: typeof ENCOUNTERS_DEADZONE !== 'undefined' ? ENCOUNTERS_DEADZONE : null
    };

    for (const [zone, arr] of Object.entries(zoneArrays)) {
        if (arr && ENCOUNTERS_MISSION[zone]) {
            arr.push(ENCOUNTERS_MISSION[zone]);
        }
    }
})();
